version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    container_name: keycloak
    command: start-dev --import-realm
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    volumes:
      - ./keycloak-data:/opt/keycloak/data/import
    networks:
      - my-network
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - my-network

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - my-network

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: backend
  #   ports:
  #     - 5000:5000
  #   networks:
  #     - my-network

networks:
  my-network:
